name: Automatic pre-release

on:
  push:
    branches: [ develop ]
  
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build for production
        run: npm run prod
      
      - name: Create tag
        uses: butlerlogic/action-autotag@1.1.2
        id: autotag
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: package
          tag_prefix: "pre."
      
      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../ESMira-web.zip .
      
      - name: Create named release
        if: ${{ steps.autotag.outputs.tagcreated == 'yes' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Pre-release version ${{ steps.autotag.outputs.version }}
          tag_name: pre.${{ steps.autotag.outputs.version}}
          prerelease: true
          generate_release_notes: true
          files: ESMira-web.zip
