name: Automatic release

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: npm run prod

      - name: Create tag
        uses: butlerlogic/action-autotag@stable
        id: autotag
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: package
          tag_prefix: "v"
        
      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../ESMira-web.zip ./*
      
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      
      - name: Publish GitHub release
        if: ${{ steps.autotag.outputs.tagcreated == 'yes' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release version ${{ steps.autotag.outputs.version }}
          tag_name: v${{ steps.autotag.outputs.version}}
          body: ${{steps.changelog.outputs.changelog}}
          files: ESMira-web.zip

      - name: Publish GitHub latest release
        if: ${{ steps.autotag.outputs.tagcreated == 'yes' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Latest release (version ${{ steps.autotag.outputs.version }})
          tag_name: latest
          body: ${{ steps.changelog.outputs.changelog }}
          files: ESMira-web.zip

      - name: Publish GitHub prerelease release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Pre release
          tag_name: prerelease
          body: ${{ steps.changelog.outputs.changelog }}
          files: ESMira-web.zip
