name: Automatic release

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: npm run prod
  
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        
      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../ESMira-web-v${{ steps.package-version.outputs.current-version}}.zip ./*
          
          
          
        
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          name: Release
          generate_release_notes: true
          files: ESMira-web-v${{ steps.package-version.outputs.current-version}}.zip
