#Thanks to https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
name: Update submodule references

on:
  push:
    branches: 
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: KL-Psychological-Methodology/ESMira
          token: ${{ secrets.KL_PUBLIC_WRITE_READ }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "Submodule bot"
          git add --all
          git commit -m "Updated submodule references" || echo "No changes to commit"
          git push
